# Generated by Django 3.0.6 on 2020-06-30 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200701_0008'),
        ('posts', '0005_auto_20200701_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.Profile'),
        ),
    ]
