# Generated by Django 3.0.6 on 2020-07-18 22:33

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200715_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=posts.models.post_image_upload),
        ),
    ]
