# Generated by Django 3.0.6 on 2020-06-30 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='active',
        ),
    ]
