# Generated by Django 3.0.6 on 2020-07-06 22:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0017_auto_20200707_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='viewers',
            field=models.ManyToManyField(blank=True, default=None, related_name='viewed_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
