# Generated by Django 3.0.6 on 2020-07-11 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_post_likers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likers',
            new_name='likes',
        ),
    ]
