# Generated by Django 3.0.6 on 2020-07-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('like', 'like'), ('comment', 'comment'), ('reply', 'reply'), ('follow', 'follow')], max_length=10, null=True),
        ),
    ]
