# Generated by Django 3.0.6 on 2020-07-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20200729_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('like', 'like'), ('comment', 'comment'), ('comment_like', 'comment_like'), ('reply', 'reply'), ('reply_like', 'reply_like'), ('follow', 'follow')], max_length=30, null=True),
        ),
    ]
