# Generated by Django 3.0.6 on 2020-07-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20200724_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='readed',
            field=models.BooleanField(default=False),
        ),
    ]
