# Generated by Django 3.0.6 on 2020-07-28 21:57

import community.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=255)),
                ('picture', models.ImageField(default='default.jpg', upload_to=community.models.community_picture_upload)),
                ('cover', models.ImageField(default='default.jpg', upload_to=community.models.community_cover_upload)),
                ('admins', models.ManyToManyField(blank=True, default=None, related_name='admin_community', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, default=None, related_name='community', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
