# Generated by Django 3.0.6 on 2020-07-14 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('admins', models.ManyToManyField(blank=True, default=None, related_name='admin_community', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, default=None, related_name='community', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
