# Generated by Django 3.0.6 on 2020-07-14 15:08

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='bio',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to=community.models.community_cover_upload),
        ),
        migrations.AddField(
            model_name='community',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to=community.models.community_picture_upload),
        ),
    ]
