# Generated by Django 3.0.6 on 2020-07-23 23:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='user-default.png', upload_to=accounts.models.profile_cover_upload),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default-cover.jpg', upload_to=accounts.models.profile_picture_upload),
        ),
    ]
