# Generated by Django 3.0.6 on 2020-07-23 23:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200724_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='default-cover.jpg', upload_to=accounts.models.profile_cover_upload),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='user-default.png', upload_to=accounts.models.profile_picture_upload),
        ),
    ]
